### ISSUE TITLE
Remove from firefox webstore

### ISSUE THREAD

**Issue by frogamic** [dtf0/zendesk-submit-expander#1]
Hi @dtf0

I appreciate that you have shared my extension with firefox users, however it is now significantly out of date and I would like to distribute the firefox version myself. Would you mind removing it from the store so that I can upload it myself under the same name?

Thanks,
Dom.

**Comment by dtf0** [comment]
Hey @frogamic, thanks for your note. I've removed the application from Mozilla Add-ons now.

Looking forward to your release and updates for Firefox.
